package com.intern.entity;

public enum ApplicationStatus {
    SUBMITTED,
    UNDER_REVIEW,
    MISSING_INFORMATION,
    CREDIT_APPROVED,
    CREDIT_REJECTED,
    LOAN_APPROVED,
    LOAN_REJECTED,
    AGREEMENT_PREPARED,
    AGREEMENT_SIGNED,
    COMPLETED,
    CANCELLED, REJECTED, FUNDS_DISBURSED, RISK_APPROVED, RISK_REJECTED, RISK_ASSESSMENT_IN_PROGRESS
}